version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-patch"]
  - dependency-name: imports-loader
    versions:
    - ">= 0"
  - dependency-name: webpack
    versions:
    - 5.20.1
    - 5.34.0
  - dependency-name: css-loader
    versions:
    - 5.2.3
